version: '3'
services:
  webserver:
    build:
      dockerfile: Dockerfile.pre
      context: .
    volumes:
      - ./index.html:/etc/nginx/templates/pre
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"