name: Container

on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    services:
      app:
        image: itismelmir/multi-server
        ports:
          - 3001:3000
        
    steps:
      - name: Log node -v
        run: |
          node -v 
          cat /etc/os-release
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
  report-message:
    runs-on: ubuntu-latest
    steps:
      - name: report by slack
        uses: docker://technosophos/slack-notify
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: "deployed to digital ocean"

        
