name: Container

on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:12
    steps:
      - name: Log node -v
        run: |
          node -v 
          cat /etc/os-release
        
